Repository appuio/component-appuio-cloud-reporting, pull requests merged in 2022-03, with the labels that each got.

#5 Don't restart invoicing on error
  component/main.jsonnet
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
Labels: enhancement

#6 Bump `erp_adapter` to `v1.0.4`
  class/defaults.yml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
Labels: dependency

#9 Update modulesync config
  .sync.yml
Labels: ignore

#12 Update dependency ghcr.io/vshn/appuio-odoo-adapter to v1.1.0
  class/defaults.yml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
Labels: dependency
