Repository appuio/component-appuio-cloud-reporting, pull requests merged in 2023-02, with the labels that each got.

#55 Enable multi-instance for this component
  class/appuio-cloud-reporting.yml
  class/defaults.yml
  component/app.jsonnet
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: enhancement

#56 Support setting the invoice title used by the ERP adapter
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
Labels: enhancement

#57 Update dependency ghcr.io/vshn/appuio-odoo-adapter to v1.9.0
  class/defaults.yml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
Labels: dependency

#59 Enable setting ORG_ID sent with Prometheus queries
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/with-org-id/appuio-cloud-reporting/apps/appuio-cloud-reporting.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/00_namespace.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/01_netpol.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/10_db_secret.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/10_erp_secret.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/10_prom_secret.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/11_backfill.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/50_alerts.yaml
  tests/with-org-id.yml
Labels: enhancement

#58 Add job to map tenant source and target from the control-api, through the billing prometheus
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/11_tenant_mapping.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/11_tenant_mapping.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/11_tenant_mapping.yaml
  tests/suspended-cronjobs.yml
Labels: enhancement

#60 Update dependency ghcr.io/appuio/appuio-cloud-reporting to v0.9.0
  class/defaults.yml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/11_backfill.yaml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/11_tenant_mapping.yaml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/11_backfill.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/11_tenant_mapping.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/11_backfill.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/11_tenant_mapping.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
Labels: dependency

#61 Update dependency ghcr.io/appuio/appuio-cloud-reporting to v0.10.0
  class/defaults.yml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/11_backfill.yaml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/11_tenant_mapping.yaml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/11_backfill.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/11_tenant_mapping.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/11_backfill.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/11_tenant_mapping.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
Labels: dependency

#62 Runbooks: Add solution for inconsistent facts in database
  docs/modules/ROOT/pages/runbooks/APPUiOCloudReportingMissingData.adoc
  docs/modules/ROOT/partials/runbooks/connect_to_postgres.adoc
  docs/modules/ROOT/partials/runbooks/find_check_logs.adoc
Labels: documentation
