Repository appuio/component-appuio-cloud-reporting, pull requests merged in 2023-03, with the labels that each got.

#63 Update dependency ghcr.io/vshn/appuio-odoo-adapter to v1.10.0
  class/defaults.yml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
Labels: dependency

#65 Update dependency ghcr.io/vshn/appuio-odoo-adapter to v1.11.0
  class/defaults.yml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/50_alerts.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/50_alerts.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/12_check_missing.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/20_invoice.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/50_alerts.yaml
Labels: dependency

#67 Add alert and runbook when tenant mapping fails
  class/defaults.yml
  docs/modules/ROOT/pages/runbooks/APPUiOCloudReportingDatabaseTenantMappingFailed.adoc
  docs/modules/ROOT/pages/runbooks/APPUiOCloudReportingMissingData.adoc
  docs/modules/ROOT/partials/nav.adoc
  tests/golden/defaults/appuio-cloud-reporting/appuio-cloud-reporting/50_alerts.yaml
  tests/golden/suspended-cronjobs/appuio-cloud-reporting/appuio-cloud-reporting/50_alerts.yaml
  tests/golden/with-org-id/appuio-cloud-reporting/appuio-cloud-reporting/50_alerts.yaml
Labels: enhancement

#68 Add Aldebaran Tech as CodeOwners
  CODEOWNERS
Labels: documentation
